### ISSUE TITLE
1101170116_M.Dzaky Ivansyah_Inverse String(perbaikan)

### ISSUE THREAD

**Issue by ivansyahiscool** [APTRG-Lab/GCS-Challenge#10]
https://github.com/APTRG-Lab/GCS-Challenge/files/2638179/11011701116_M.Dzaky.Ivansyah_Inverse.String.2.0.zip

**Comment by wianoski** [comment]
It was clean code, if you added some comments so common people who read your code can understand it, keep the work on 👍
