### ISSUE TITLE
6705180062_I Gusti Ngurah Bagus Dimas Wiradyaksa_Matriks3x3(Penjumlahan, Pengurangan, Perkalian)

### ISSUE THREAD

**Issue by ngurahdimaas** [APTRG-Lab/GCS-Challenge#11]
Matriks 3x3 (Penjumlahan, Pengurangan, Perkalian)

[Matriks 3x3.txt](https://github.com/APTRG-Lab/GCS-Challenge/files/2638604/Matriks.3x3.txt)

**Comment by wianoski** [comment]
It is fine, but you need to explain it, like comments, and user guided on the program, keep it up boy 👍
