### ISSUE TITLE
1301180353_Jordi Yaputra_Algoritma mencari jalan paling efisien untuk waypoint pada wahana

### ISSUE THREAD

**Issue by jordiyapz** [APTRG-Lab/GCS-Challenge#4]
`
[Algoritma Jalan terpendek pada ClosedLoop (by Jordi Yaputra).txt](https://github.com/APTRG-Lab/GCS-Challenge/files/2636085/Algoritma.Jalan.terpendek.pada.ClosedLoop.by.Jordi.Yaputra.txt)
`

**Comment by wianoski** [comment]
Clean Pseudocode, everything is clear except next time coba implementasi ke dalam pythonnya kalo udah masuk kay :+1:

**Comment by jordiyapz** [comment]
Ashiiyap
Okee, Bang
