### ISSUE TITLE
Yusuf Hamzah Ruhiyat_1102180193_HelloWorld

### ISSUE THREAD

**Issue by Yusufhr02** [APTRG-Lab/GCS-Challenge#5]

**Comment by Yusufhr02** [comment]
Link https://drive.google.com/file/d/14hbYnrUiHWGBQW3wquPobLW4uS6_cjSS/view?usp=drivesdk

**Comment by Yusufhr02** [comment]
Link terbaru
https://drive.google.com/file/d/1Wgx1YN6Dhq6dtEoCVu1cEXeb6olbuxcM/view?usp=drivesdk

**Comment by wianoski** [comment]
Well, its kinda simple code, but okay, next time try to discover another example okay
