### ISSUE TITLE
6705180070_Rofi Rezkin_Konversi Angka ke Huruf

### ISSUE THREAD

**Issue by rofirezkin** [APTRG-Lab/GCS-Challenge#8]
[Perjuangan Rekrutasi APTRG.txt](https://github.com/APTRG-Lab/GCS-Challenge/files/2637032/Perjuangan.Rekrutasi.APTRG.txt)

**Comment by wianoski** [comment]
Well Done !, its looks like simple program, but you nailed it ! nice work ! 👍
